// <auto-generated />
using ApiFacer.DB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiFacer.Migrations
{
    [DbContext(typeof(ApiDB))]
    [Migration("20240218165438_faiser")]
    partial class faiser
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.13");

            modelBuilder.Entity("ApiFacer.Classes.Events", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("path")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Events");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Future Games 2024",
                            path = "FutureGames2024"
                        },
                        new
                        {
                            Id = 2,
                            Name = "10 Future Games 2023",
                            path = "10FutureGames2023"
                        });
                });

            modelBuilder.Entity("ApiFacer.Classes.Logins", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("id_role")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ipAdress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("sessionkey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("userId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Logins");
                });

            modelBuilder.Entity("ApiFacer.Classes.Roles", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            name = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            name = "Фотограф"
                        });
                });

            modelBuilder.Entity("ApiFacer.Classes.Users", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("first_name")
                        .HasColumnType("TEXT");

                    b.Property<int>("id_role")
                        .HasColumnType("INTEGER");

                    b.Property<string>("last_name")
                        .HasColumnType("TEXT");

                    b.Property<string>("login")
                        .HasColumnType("TEXT");

                    b.Property<string>("password")
                        .HasColumnType("TEXT");

                    b.Property<string>("surname")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            first_name = "Арсений",
                            id_role = 1,
                            last_name = "А",
                            login = "root",
                            password = "rimezaaa",
                            surname = "Артюхин"
                        });
                });

            modelBuilder.Entity("ConsoleFaiserScript.Classes.PersonVk", b =>
                {
                    b.Property<int>("userImagesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("age")
                        .HasColumnType("INTEGER");

                    b.Property<double>("arousal")
                        .HasColumnType("REAL");

                    b.Property<double>("awesomeness")
                        .HasColumnType("REAL");

                    b.Property<double>("confidence")
                        .HasColumnType("REAL");

                    b.Property<string>("emotion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("frontality")
                        .HasColumnType("REAL");

                    b.Property<string>("sex")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("similarity")
                        .HasColumnType("REAL");

                    b.Property<string>("tag")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("valence")
                        .HasColumnType("REAL");

                    b.Property<double>("visibility")
                        .HasColumnType("REAL");

                    b.HasKey("userImagesId");

                    b.ToTable("PersonVk");
                });

            modelBuilder.Entity("ConsoleFaiserScript.Classes.UserImages", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("eventId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("localPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("userId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("yandexPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("UserImages");
                });
#pragma warning restore 612, 618
        }
    }
}
